### ISSUE TITLE
Active day in the calendar not colored in the dark theme

### ISSUE THREAD

**Issue by devbn3li** [wellingtonmwadali/ALX_MultiTone-Magic#50]
![Screenshot (96)](https://github.com/wellingtonmwadali/ALX_MultiTone-Magic/assets/76428295/5dad36fb-3dff-43c9-b00a-b061b270ac46)

**Comment by wellingtonmwadali** [comment]
I shall work on it today.

Thanks for the feedback.

**Comment by wellingtonmwadali** [comment]
The active day in the calendar is now colored in dark theme.

**Comment by devbn3li** [comment]
Good job keep going
